services:
  - type: web
    name: disaster-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 123456789
      - key: DB_NAME
        value: disaster_management

